version: 1.13.0.{build}
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: $(appveyor_repo_commit)
before_build:
- cmd: >-
    git submodule update --init --recursive

    nuget restore OverwatchToolchain.sln
build:
  project: OverwatchToolchain.sln
  verbosity: minimal
before_package:
- cmd: >-
    del /F /Q dist\Release\*.pdb

    del /F /Q dist\Release\*.xml

    del /F /Q CASCExplorer\CASCExplorer\bin\Release\*.pdb

    del /F /Q CASCExplorer\CASCExplorer\bin\Release\*.xml
artifacts:
- path: dist/Release
  name: toolchain-release
- path: dist/Release/CascLib.dll
  name: CascLib
- path: CASCExplorer/CASCExplorer/bin/Release
  name: CASCExplorer
